// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbvnfbjstokjachzuyvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtidm5mYmpzdG9ramFjaHp1eXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTA1MTIsImV4cCI6MjA2OTk2NjUxMn0.eaSzI1stNa1vsEqoG48EB-qllvBCWkL3NcSPLgCYxQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});